### ISSUE TITLE
Windows support

### ISSUE THREAD

**Issue by pratham2003** [yhirose/vscode-filtertext#12]
I'm able to make things like "sort" and "uniq" work on Windows using GNU CoreUtils for Windows : http://gnuwin32.sourceforge.net/install.html

But I'm unable to pass parameters on Windows.
e.g. "sort -h"

The error I get is
Command exits (status: 1) with error message:
-hThe system cannot find the file specified.

**Comment by yhirose** [comment]
@pratham2003, thanks for the report. Could you configure the following settings to setup your bash path properly?

 * filterText.invokeViaBash.windows
 * filterText.bashPath.windows

You can get more information about it at #10.

**Comment by johnnytemp** [comment]
I think you have invoked the `C:\Windows\System32\sort.exe` instead of the GNU's version.  Please check your PATH environment variable.

### To check which `sort` command you are using

- Press Win-R key, type `cmd` and Enter, to open Window's command prompt.
- Type `where sort` and Enter.  If it is using "C:\Windows\System32\sort.exe", it will print it out.
- `C:\Windows\System32\sort.exe -h` will gives the error "-hThe system cannot find the file specified."

**Comment by johnnytemp** [comment]
And if you have installed Git on windows, it should have installed a bash program at `C:\Program Files\Git\bin\bash.exe`.  If this exists, you could consider using bash shell, and use that path as the value for "filterText.bashPath.windows", and set `"filterText.invokeViaBash.windows": true`.
